name = "websocket-server"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-05-08"
# compatibility_flags = ["nodejs_compat"]

# TODO: Add your Cloudflare account ID here
# Find it in Cloudflare Dashboard > Overview (right sidebar)
account_id = "3f7282dd7e726f4414b70698b0b4fd5b"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-sync-cf-demo"
database_id = "1c9b5dae-f1fa-49d8-83fa-7bd5b39c4121"
# database_id = "${LIVESTORE_CF_SYNC_DATABASE_ID}"

[vars]
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
